### ISSUE TITLE
Windows unit tests are broken

### ISSUE THREAD

**Issue by mctavish** [googleapis/cloud-debug-nodejs#1187]
Not related to a code change in this repository, unit tests on windows started failing on or before 19 Oct 2023.

The failure is as follows:

1) v8debugapi
       set and wait
         should report error for native prop or getter:
     Uncaught TypeError: Cannot read property 'some' of undefined
      at D:\a\cloud-debug-nodejs\cloud-debug-nodejs\build\test\test-v8debugapi.js:987:46
      at D:\a\cloud-debug-nodejs\cloud-debug-nodejs\build\test\test-v8debugapi.js:188:25
      at Immediate.<anonymous> (build\src\agent\v8\inspector-debugapi.js:37:94)
      at processImmediate (internal/timers.js:464:21)

  2) v8debugapi
       "after each" hook for "should report error for native prop or getter":

      AssertionError [ERR_ASSERTION]: there should be no breakpoints active
      + expected - actual

      -1
      +0
      
      at stateIsClean (build\test\test-v8debugapi.js:42:12)
      at Context.<anonymous> (build\test\test-v8debugapi.js:201:16)
      at processImmediate (internal/timers.js:464:21)

**Comment by mctavish** [comment]
A bit of further investigation:

On non-windows tests, the failing test will have the following value for the `hasGetter` expression:
```
{
  value: 'Object',
  members: [
    { name: '_a', value: '5' },
    { name: 'a', varTableIndex: 2 },
    { name: 'b', value: 'hello world' }
  ]
}
```

On Windows, the value is:
```
{
  status: StatusMessage {
    refersTo: 'VARIABLE_VALUE',
    description: { format: 'Max data size reached' },
    isError: true
  }
}
```
