### ISSUE TITLE
Cannot read property 'indexOf' of undefined on Breakpoint Hit

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/cloud-debug-nodejs#457]
As specified by @xp500 in issue #391:

> @DominicKramer I've set up the debugger in our production servers but when the breakpoint hits I get the following error: Error trying to capture snapshot data: TypeError: Cannot read property 'indexOf' of undefined

> The full stack trace is
```
Error trying to capture snapshot data: TypeError: Cannot read property 'indexOf' of undefinedTypeError: Cannot read property 'indexOf' of undefined at StateResolver.isPathInCurrentWorkingDirectory_ (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/state/legacy-state.ts:301:17
 at StateResolver.shouldFrameBeResolved_ (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/state/legacy-state.ts:262:15
 at StateResolver.resolveFrames_ (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/state/legacy-state.ts:248:16
 at StateResolver.capture_ (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/state/legacy-state.ts:172:25
 at Object.capture (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/state/legacy-state.ts:569:8
 at V8DebugApi.captureBreakpointData (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/v8/legacy-debugapi.ts:458:30
 at V8DebugApi.onBreakpointHit (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/v8/legacy-debugapi.ts:384:12
 at eventData.breakPointsHit.forEach.hit (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/v8/legacy-debugapi.ts:83:41
 at V8DebugApi.handleDebugEvents (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/v8/legacy-debugapi.ts:79:44
```
> Any idea of what could be going wrong? Running the same code locally works perfectly

**Comment by DominicKramer** [comment]
I'm not sure how to reproduce this.  Looking at the code, I'm not sure how the error you were seeing is possible.  Have you seen this error again since you have reported it?  Thanks.

**Comment by xp500** [comment]
Unfortunately not, since I'm stuck on #530

We can close this and once I get through that other issue I can start testing again :)

**Comment by DominicKramer** [comment]
Ok sounds good.  I will let you know of progress on addressing #530.

**Comment by DominicKramer** [comment]
Sorry I missed updating this thread sooner, but issue #530 has been fixed.
