### ISSUE TITLE
Circular object tests are failing on master for Node 12+

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/cloud-debug-nodejs#742]
On Node 12, the tests for analyzing circular objects are failing ([link](https://source.cloud.google.com/results/invocations/e2f12849-6f52-40ff-9a5a-56ac9153da8b/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fcontinuous%2Fgoogleapis%2Fcloud-debug-nodejs%2Fnode12%2Ftest/log)).

The following is the relevant error:
```
1) /tmpfs/src/github/cloud-debug-nodejs/build/test/test-circular.js
       Should be able to read the argument and the context:
      Uncaught AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:
1372 !== 3
      + expected - actual
      -1372
      +3
      at /tmpfs/src/github/cloud-debug-nodejs/test/test-circular.ts:111:16
      at Immediate._onImmediate (src/agent/v8/inspector-debugapi.ts:238:11)
      at processImmediate (internal/timers.js:439:21)
  2) /tmpfs/src/github/cloud-debug-nodejs/build/test/test-circular.js
       "after each" hook for "Should be able to read the argument and the context":
      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: there should be no breakpoints active
      + expected - actual
      -1
      +0
      at stateIsClean (test/test-circular.ts:32:10)
      at Context.<anonymous> (test/test-circular.ts:77:12)
      at processImmediate (internal/timers.js:439:21)
  3) /tmpfs/src/github/cloud-debug-nodejs/build/test/test-this-context.js
       Should be able to read the argument and the context:
      Uncaught AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: There should be three locals
      + expected - actual
      -2
      +3
      at /tmpfs/src/github/cloud-debug-nodejs/test/test-this-context.ts:106:18
      at Immediate._onImmediate (src/agent/v8/inspector-debugapi.ts:238:11)
      at processImmediate (internal/timers.js:439:21)
  4) /tmpfs/src/github/cloud-debug-nodejs/build/test/test-this-context.js
       "after each" hook for "Should be able to read the argument and the context":
      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: there should be no breakpoints active
      + expected - actual
      -1
      +0
      at stateIsClean (test/test-this-context.ts:32:10)
      at Context.<anonymous> (test/test-this-context.ts:79:12)
      at processImmediate (internal/timers.js:439:21)
```

**Comment by DominicKramer** [comment]
I have opened PR #743 that temporarily disables the test in question so that the other pending PRs can land.  As part of addressing this issue, the test should be re-enabled.

**Comment by kjin** [comment]
This is a Node regression due to https://bugs.chromium.org/p/chromium/issues/detail?id=906847. The best we can do right now is warn users not to use maxDataSize=0 on Node 12+.
